---
services:
  samba:
    image: dockurr/samba
    container_name: samba
    restart: always
    ports:
      - 445:445
    volumes:
      - $SAMBA_SHARE:/storage
    environment:
      NAME: $SAMBA_NAME
      USER: $SAMBA_USER
      PASS: $SAMBA_PASS
