---

services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: always
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - $SAMBA_SHARE:/shares/main
    environment:
      - GROUP_$SAMBA_ID=$SAMBA_GROUP_UID
      - ACCOUNT_$SAMBA_ID=$SAMBA_PASSWORD
      - UID_$SAMBA_ID=$SAMBA_UID
      - GROUPS_$SAMBA_ID=$SAMBA_ID
      - SAMBA_VOLUME_CONFIG_main: |
          [main]
          valid users = $SAMBA_ID
          path = /shares/main
          guest ok = no
          read only = no
          browseable = yes
