---
services:
  # VPN client for internal use
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    hostname: mort
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - $TAILSCALE_STATE:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    networks:
      - internal_use_net
  
  # Reverse proxy for internal use applications
  private_caddy:
    image: caddybuilds/caddy-cloudflare:alpine
    container_name: private_caddy
    restart: unless-stopped
    volumes:
      - $CADDYFILE:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=$CLOUD_FLARE_TOKEN
    depends_on:
      - tailscale
    network_mode: service:tailscale

networks:
  private_proxy_network:
    external: true

volumes:
  caddy_data:
  caddy_config: