---
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - $AUDIOBOOKSHELF_PORT:80
    volumes:
      - $AUDIOBOOKS_LIBRARY:/audiobooks
      - $PODCASTS_LIBRARY:/podcasts
      - $AUDIOBOOKSHELF_CONFIG:/config
      - metadata:/metadata
    environment:
      - TZ=$AUDIOBOOKSHELF_TZ
    networks:
      - private_proxy_network

networks:
  private_proxy_network:
    external: true

volumes:
  metadata: