services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: pihole-tailscale
    hostname: pihole
    restart: unless-stopped
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    dns:
      - 127.0.0.1
      - 8.8.8.8
    volumes:
      - $TAILSCALE_STATE:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
  
  pihole_tailscale:
    container_name: pihole_tailscale
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: $PIHOLE_PASSWORD
      FTLCONF_dns_listeningMode: 'all'
      PIHOLE_UID: $PIHOLE_UID
      PIHOLE_GID: $PIHOLE_GID
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - $PIHOLE_VPN_CONFIG:/etc/pihole
    cap_add:
      - net_admin
      - sys_nice
    restart: unless-stopped
    network_mode: service:tailscale

  pihole_local:
    container_name: pihole_local
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Berlin'
      FTLCONF_webserver_api_password: $PIHOLE_PASSWORD
      FTLCONF_dns_listeningMode: 'all'
      FTLCONF_webserver_port: '8080,4443s'
      PIHOLE_UID: $PIHOLE_UID
      PIHOLE_GID: $PIHOLE_GID
    network_mode: "host"
    dns:
      - 127.0.0.1
      - 1.1.1.1
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - $PIHOLE_LOCAL_CONFIG:/etc/pihole
    cap_add:
      - net_admin
      - sys_nice
    restart: unless-stopped
