---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: $JELLYFIN_USER
    restart: always
    volumes:
      - $JELLYFIN_CONFIG:/config
      - $JELLYFIN_CACHE:/cache
      - $JELLYFIN_MEDIA:/media
    environment:
      - JELLYFIN_PublishedServerUrl=http://watch.the.randomaether.com
    networks:
      - private_proxy_network

networks:
  private_proxy_network:
    external: true