---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    cputemp: true
    tempmax: 100 # optional, maximum cpu temp

- search:
    provider: duckduckgo
    target: _blank
